local VisualSettings = {
	["car.defaultlight.day.emissive.on"] = 400.0,
	["car.defaultlight.night.emissive.on"] = 400.0
}

CreateThread(function()
	for k,v in pairs(VisualSettings) do
		SetVisualSettingFloat(k, v+.0)
	end
end)

CreateThread(function()
	-- PD/SH
	AddTextEntry("iv20polchar", "2020 Charger")
	AddTextEntry("ivdirtbike", "Dirtbike")
	AddTextEntry("ivpolas350", "AS350")
	AddTextEntry("ivpolchar", "Charger")
	AddTextEntry("ivpolexp", "Explorer")
	AddTextEntry("ivpolchal", "challenger")
	AddTextEntry("ivpolstang", "Mustang")
	AddTextEntry("ivpolvette", "Corvette")
	AddTextEntry("bcat", "BearCat")
	AddTextEntry("mrap", "MRAP")
	AddTextEntry("riot3", "BearCat 2")
	AddTextEntry("ivpolmm", "Motor")
	AddTextEntry("ivpolraptor", "Raptor")
	AddTextEntry("ivpoltah", "Tahoe")
	AddTextEntry("ivpoltaurus", "Taurus") 
	AddTextEntry("ivpolvic", "Cruiser")
	AddTextEntry("legacy7", "F150")
	AddTextEntry("legacy15", "Chevrolet Silverado")
	AddTextEntry("HILLBOATY", "HILLBILLY")
	AddTextEntry("largeboat", "Large boat")
	AddTextEntry("smallboat", "Small boat")
	AddTextEntry("infpolstang", "Mustang 2025")
	AddTextEntry("2025riotcat", "riotcat 2025")
	AddTextEntry("fmod", "fmod")
	AddTextEntry("fmodriot", "riot")
	AddTextEntry("pitbull", "pitbull")
	AddTextEntry("riothuey", "riothuey")
	AddTextEntry("riotpitbull", "riotpitbull")
	AddTextEntry("swatcat", "swatcat")
	AddTextEntry("leg23cam", "Camaro 2023")
	AddTextEntry("bmwbike", "BMW R1200")
	AddTextEntry("swatvanr2", "Swat Van 2")
	AddTextEntry("s97raider", "Sikorsky S97")
-- Federal
	AddTextEntry("ivvalkyrie", "Valkyrie")
	AddTextEntry("mh60l", "MH-60L DAP")
	AddTextEntry("onebeast", "Cadillac The Beast")
	AddTextEntry("pdh1alpha", "Hummer H1 Alpha")
	AddTextEntry("um16tahoe", "Tahoe Unmark")
	AddTextEntry("viperleo", "Viper")
	AddTextEntry("ivjdford", "F150 Unmark")
	AddTextEntry("SWATVAN", "Swat Van")
	AddTextEntry("350eod", "Rescue Team")
	AddTextEntry("infpolcls2015", "Benz CLS 2015")
	AddTextEntry("infpol69charger", "69charger")
	AddTextEntry("M5RB_VV", "M5 Unmark")
	-- Free Jobs
	AddTextEntry("nspeedo", "Van Speedo")
	AddTextEntry("inffaggio", "Faggio")
	AddTextEntry("OILTANKER", "MTL Oil Tanker ")
	-- Mechanic
	AddTextEntry("17silv", "Mechanic Silverado")
	AddTextEntry("21f250", "Mechanic F250")
	AddTextEntry("21tahoe", "Mechanic Tahoe")
	AddTextEntry("f350worktruck", "Mechanic Manster")
	AddTextEntry("flatbedm2", "Flatbed")
	AddTextEntry("ivtowtruck", "towtruck")
	AddTextEntry("mcford", "Mechanic F150")
	AddTextEntry("uh1calfire", "Mechanic calfire")
	AddTextEntry("dbx", "Aston Martin DBX")
	AddTextEntry("23sirhd", "Mechanic GMC")
	AddTextEntry("22bmw", "Mechanic BMW")
	AddTextEntry("m5g60w", "Mechanic M5")
	-- Medic
	AddTextEntry("18TahoeAMR", "Medic Tahoe")
	AddTextEntry("22FPIUAMR", "Medic Explorer")
	AddTextEntry("alifeliner", "alifeliner")
	AddTextEntry("ambulance1", "Ambulance Van")
	AddTextEntry("emsa", "Ambulance")
	AddTextEntry("emsaw139", "AgustaWestland AW139")
	AddTextEntry("emsv", "Medic Coroner")
	AddTextEntry("fd2", "Medic Charger")
	AddTextEntry("polgs350", "Medic Lexus")
	AddTextEntry("zendrack", "Medic Benz")
	AddTextEntry("polgt17", "Medic Ford GT")
	AddTextEntry("GSD25EMSDur", "GSD25EMSDur")
	-- Taxi
	AddTextEntry("e63amg", "Taxi E63")
	AddTextEntry("f812", "Taxi Ferrari")
	AddTextEntry("ivtaxi", "Taxi Cruiser")
	AddTextEntry("taxi", "Taxi Ford")
	AddTextEntry("taxi2", "Taxi Charger")
	AddTextEntry("taxi3", "Taxi Declasse")
	AddTextEntry("taxi4", "Taxi Alpha Romeo")
	AddTextEntry("taxi5", "Taxi Tesla")
	AddTextEntry("transmbv250", "Taxi Van")
	AddTextEntry("taxigs350", "Taxi Lexus")
	AddTextEntry("taxia45", "Benz A45")
	AddTextEntry("taxie500", "Benz E500")
	-- Weazel
	AddTextEntry("newsmav", "News Heli")
	AddTextEntry("rumpo", "News Van")
	AddTextEntry("fascalamo2", "Weazel News Storm")
	-- Others
	AddTextEntry("69charger", "Charger 1969")
	AddTextEntry("deluxo6str", "Deluxo Punk")
	AddTextEntry("evo9", "Lancer Evo")
	AddTextEntry("hh60g", "Sikorsky HH-60")
	AddTextEntry("ivjourney", "Journey")
	AddTextEntry("ivwheelchair", "Wheelchair")
	AddTextEntry("ts20", "Enzo Supra")
	AddTextEntry("dodgebseries", "Dodge Halloween")
	AddTextEntry("Killer370zH", "GTR Halloween")
	AddTextEntry("parselx", "Peugeot Pars ELX")
	AddTextEntry("206", "Peugeot 206 GT")
	AddTextEntry("405glx", "Peugeot 405 GLX")
	AddTextEntry("hondagc", "Honda GC")
	AddTextEntry("gcscoot", "Scooter")

	-- vanilla
	AddTextEntry("bus", "Taxi Bus")
	AddTextEntry("stockade", "Armored Truck") 
	-- VIP Cars
	AddTextEntry("19raptor", "Raptor 2019")
	AddTextEntry("600lt", "McLaren 600LT")
	AddTextEntry("2022kiak5gt", "2022 Kia K5 GT")
	AddTextEntry("ageraone", "Koenigsegg Agera One")
	AddTextEntry("amggt63s", "Amg Gt 63S")
	AddTextEntry("amggtc", "AMG GT C")
	AddTextEntry("amgone", "AMG ONE")
	AddTextEntry("ap2", "Honda S2000")
	AddTextEntry("bdragon", "Bentley Dragon")
	AddTextEntry("benze55", "Benz E55")
	AddTextEntry("bmci", "BMW M5")
	AddTextEntry("bmwg07", "BMW X7")
	AddTextEntry("brabus850", "BRABUS 850")
	AddTextEntry("brabusrocket900", "BRABUS Rocket")
	AddTextEntry("c7", "Corvette C7")
	AddTextEntry("c63w205", "AMG C63s")
	AddTextEntry("camry55", "Toyota Camry ")
	AddTextEntry("cb650r", "Honda CB 650R")
	AddTextEntry("coastline", "Rolls-Royce Coastline")
	AddTextEntry("crownrs", "MERCEDES GLS MAYBACH")
	AddTextEntry("dc_evo900mansoryv2", "MANSORY P9LM EVO 900")
	AddTextEntry("fd", "Mazda RX-7")
	AddTextEntry("flyspur24m", "Mansory flyspur24m")
	AddTextEntry("fordbatman", "Ford Batman")
	AddTextEntry("gcmlamboultimae", "Lamborghini Aventador Ultimae")
	AddTextEntry("golfr18", "Volkswagen Golf R18")
	AddTextEntry("gonzo_sierraev", "GMC SIERRA EV DENALI")
	AddTextEntry("gtr", "Nissan GTR")
	AddTextEntry("haya24nbrt", "Suzuki Hayabusa")
	AddTextEntry("hyundaiveloster", "Hyundai Veloster")
	AddTextEntry("i8", "BMW i8")
	AddTextEntry("ikx3_coda22", "Pagani")
	AddTextEntry("ikx3_se24", "Lamborghini Urus")
	AddTextEntry("ikx3_turbogt22", "Porsche Cayenne")
	AddTextEntry("ikx3ev22", "GMC Hummer")
	AddTextEntry("ikx3formentor21", "CUPRA Formentor")
	AddTextEntry("ikx3gtblack", "AMG GT Black Series")
	AddTextEntry("ikx3rezvani", "Rezvani TANK")
	AddTextEntry("kg300", "Charger KG300")
	AddTextEntry("lc500", "Lexus LC500")
	AddTextEntry("lxlfa", "Lexus LFA")
	AddTextEntry("m3e46", "BMW M3")
	AddTextEntry("m4f82", "BMW M4")
	AddTextEntry("m5", "BMW M5")
	AddTextEntry("mers18", "Megan RS")
	AddTextEntry("motobumblebee", "Bumble Bee")
	AddTextEntry("mst", "Ford Mustang")
	AddTextEntry("nissantitan17", "Nissan Titan")
	AddTextEntry("overdose", "Rolls-Royce Wraith Overdose")
	AddTextEntry("p1", "McLaren P1")
	AddTextEntry("pbavatarangin", "Avatar")
	AddTextEntry("peykan", "Peykan")
	AddTextEntry("pistas", "Ferrari 488 Pista")
	AddTextEntry("por911", "Porsche 911")
	AddTextEntry("q50s2023WBV2", "Infinity Q50S")
	AddTextEntry("q820", "Audi Q8")
	AddTextEntry("r8irobot", "Audi RSQ")
	AddTextEntry("r8v10abt", "Audi R8 V10")
	AddTextEntry("r820", "Audi R8")
	AddTextEntry("ram226x6", "Ram 6x6")
	AddTextEntry("regera16", "Koenigsegg Regera")
	AddTextEntry("rmodrs7", "Audi RS7")
	AddTextEntry("rmodx6", "BMW X6")
	AddTextEntry("rrghost21", "RR Ghost")
	AddTextEntry("sah6", "Toyota Khargoshi")
	AddTextEntry("sclkuz", "Toyota Land Cruiser")
	AddTextEntry("sf12", "Ferrari SF12")
	AddTextEntry("skyline", "Nissan Skyline")
	AddTextEntry("theramtrx21", "Ram TRX")
	AddTextEntry("tsgr20", "Supra GR")
	AddTextEntry("w463a1", "Brabus G800")
	AddTextEntry("wraithbeast", "RR Wraith Mafia Beast")
	AddTextEntry("x3gemwb", "Koenigsegg Gemera")
	AddTextEntry("y1700max", "Yamaha VMAX")
	AddTextEntry("722s", "Benz SLR Mansory")
	AddTextEntry("cls2015", "BENZ CLS")
	AddTextEntry("mlnovitec", "Maserati Levante")
	AddTextEntry("infdaemon", "Daemon Motor")
	AddTextEntry("w223b50", "Brabus B50")
	AddTextEntry("widekit2024gtdd", "Ford GT 350")
	AddTextEntry("challenger23d", "Challenger 2023")
	AddTextEntry("charger23d", "Charger 2023")
	AddTextEntry("bmwi7m70i", "BMW i7")
	AddTextEntry("ikx3_tour26", "Bugatti Tourbillon 2026")
	AddTextEntry("Purosanguebeast", "Ferrari Purosangue Beast")
	AddTextEntry("venuumtt", "Audi Venuum")
	AddTextEntry("xxxxx", "Rezvani Hercules 6x6")
	AddTextEntry("19sorento", "Sorento 2019")
	AddTextEntry("cb1300", "Honda CB 1300")
	AddTextEntry("civichycade2", "Honda Civic")
	AddTextEntry("g63m", "AMG G63")
	AddTextEntry("nathanobsford", "Nathan OBS Ford")
	AddTextEntry("noire19wb", "Mercedes-Benz Noire")
	AddTextEntry("peptos_h2", "Peptos H2")
	AddTextEntry("xantia", "Citroen Xantia")
	AddTextEntry("bmwm4", "BMW M4 NEW")
	AddTextEntry("aventsvjr", "Lamborghini Aventador")
	AddTextEntry("gxr35", "Nissan GTR New")
	AddTextEntry("demon", "Dodge Demon")
	AddTextEntry("lambobarbie", "Gallardo Barbie")
	AddTextEntry("ikx3_m390", "BMW M3 1990")
	AddTextEntry("ikx3_senna20", "McLaren Senna")
	AddTextEntry("ikx3_sss65024", "Shelby Super Snake")

	-- Useless
		--Others
	AddTextEntry("17jamb", "Camper")
	AddTextEntry("bbdawn", "Dragon")
	AddTextEntry("chillybin", "Ice")
	AddTextEntry("cp9a", "Lancer")
	AddTextEntry("db11", "Aston Martin DB11")
	AddTextEntry("dilettante2", "Driving School")
	AddTextEntry("etotti", "Benz E350")
	AddTextEntry("exor", "ZL1")
	AddTextEntry("f10m5rc", "BMW mini")
	AddTextEntry("glynx", "Westland Lynx")
	AddTextEntry("ikx3_n22", "Hyundai")
	AddTextEntry("ikx393519", "Porsche 935")
	AddTextEntry("pitbullbb", "Pitbull")
	AddTextEntry("yukon", "GMC")
	AddTextEntry("taxipeugeot", "Taxi Peugeot ")

		-- VIP Cars
	AddTextEntry("10r24nbrt", "Kawasaki Ninja")
	AddTextEntry("17r35", "Nissan GT-R")
	AddTextEntry("296gts", "Ferrari 296 GTS")
	AddTextEntry("650e", "Boat")
	AddTextEntry("918lbwk", "Porsche 918 Spyder")
	AddTextEntry("a80", "Supra A80")
	AddTextEntry("acty", "scooby doo")
	AddTextEntry("amels200", "Amels 200")
	AddTextEntry("bmwm8", "BMW M8")
	AddTextEntry("bmwr75bobber", "BMW R75 Bobber")
	AddTextEntry("bossprior", "Mustang Boss Prior")
	AddTextEntry("brunner", "Brunner Classic")
	AddTextEntry("cl65", "AMG CL65")
	AddTextEntry("coldsjokercat", "SRT Joker")
	AddTextEntry("cx75", "Jaguar C-X75")
	AddTextEntry("cz4a", "Lancer")
	AddTextEntry("dbmk4hycade", "Supra")
	AddTextEntry("enzo", "Ferrari Enzo")
	AddTextEntry("fenyr", "Fenyr")
	AddTextEntry("fer296beast", "Ferrari 296")
	AddTextEntry("fer488beast", "Ferrari 488")
	AddTextEntry("gcmferraripurosangue", "Ferrari Purosangue")
	AddTextEntry("gcmtemerario", "Lamborghini Temerario")
	AddTextEntry("giulia_2021", " Alfa Romeo Giulia")
	AddTextEntry("glsmansory850", "Mansory GLS 850")
	AddTextEntry("godzmbg900", "Maybach G900")
	AddTextEntry("gstjcr1", "GST")
	AddTextEntry("ikx3_c800b", "Lamborghini Huracan")
	AddTextEntry("ikx3_fc812", "Ferrari 812")
	AddTextEntry("ikx3_gr21rb", "Toyota GR Yaris")
	AddTextEntry("ikx3_sl6321", "AMG SL63")
	AddTextEntry("ikx3_xxs24", "Ferrari SF90")
	AddTextEntry("ikx3charger9", "Charger SRT")
	AddTextEntry("ikx3daytona22", "Ferrari Daytona")
	AddTextEntry("ikx3ioniq23", "Hyundai IONIQ 5")
	AddTextEntry("ikx3ix22", "BMW IX")
	AddTextEntry("ikx3lanzador", "Lamborghini Lanzador")
	AddTextEntry("jeslbwk", "Koenigsegg Jesko")
	AddTextEntry("killerf8", "Ferrari Killer")
	AddTextEntry("lamborghinihuracan_novitec2020wb", "HURACAN NOVITEC")
	AddTextEntry("lamborghinisian", "Lamborghini SIAN")
	AddTextEntry("lrlwb22", "Range Rover SV")
	AddTextEntry("m4comp", "BMW M4 Competition")
	AddTextEntry("mercxclass", "Benz X-Class")
	AddTextEntry("msf8cp22", "Mansory P880")
	AddTextEntry("mvisiongt", "AMG Vision GT")
	AddTextEntry("mvso", "MVSO")
	AddTextEntry("na1", "Honda N-One")
	AddTextEntry("nc1", "Honda nsx nc1")
	AddTextEntry("nis180", "Nissan 180SX")
	AddTextEntry("noire19wb", "Bugatti La Voiture Noire")
	AddTextEntry("pb350z", "Nissan Fairlady Z")
	AddTextEntry("pbfl5nfs", "CIVIC TypeR")
	AddTextEntry("r1", "Honda R1")
	AddTextEntry("rboat", "R Boat")
	AddTextEntry("rmodamgc63", "AMG C63s")
	AddTextEntry("rmodbmwi8", "BMW I8")
	AddTextEntry("rmodlp750", "Aventador LP750")
	AddTextEntry("rmodm4gts", "BMW M4 GTS")
	AddTextEntry("rmodmustang", "Ford Mustang")
	AddTextEntry("romaultimate", "Lamborghini Rome")
	AddTextEntry("rs62", "Audi RS6")
	AddTextEntry("runner", "Runner Motor")
	AddTextEntry("silviajdm", "Nissan Silvia")
	AddTextEntry("sr650fly", "VIP Boat")
	AddTextEntry("suprahycade", "Supra Turbo")
	AddTextEntry("tecnomar63", "LAMBORGHINI Boat")
	AddTextEntry("teslapd", "Tesla")
	AddTextEntry("themustdh", "Mustang DH")
	AddTextEntry("x3brzrowen", "Subaru BRZ")
	AddTextEntry("x5xdriver", "BMW X5")
end)